version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app/backend
      - ./logs:/app/logs
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://coinage_user:coinage_pass@postgres:5432/coinage_db
    depends_on:
      - postgres
      - redis
      - jaeger

  postgres:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=coinage_db
      - POSTGRES_USER=coinage_user
      - POSTGRES_PASSWORD=coinage_pass
    ports:
      - "5432:5432"

  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"

  jaeger:
    image: jaegertracing/all-in-one:1.37
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"

  prometheus:
    image: prom/prometheus:v2.35.0
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:8.5.3
    volumes:
      - ./monitoring/grafana_dashboard.json:/var/lib/grafana/dashboards/coinage_dashboard.json
    ports:
      - "3000:3000"

volumes:
  postgres_data:
  grafana_data:

networks:
  coinage_network:
    driver: bridge
